services:
  service:
    build: .
    image: payment-service-image
    container_name: payment-service
    restart: always
    ports:
      - "5005:4005"
    env_file:
      - .env
    networks:
      - users-kafka-net
    
networks:
  users-kafka-net:
    external: true